name: invlog_test
description: A new Flutter project with Firebase Authentication.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^3.5.7

  # Authentication & State Management
  google_sign_in: ^6.3.0
  provider: ^6.1.2

  # Storage & Files
  flutter_secure_storage: ^10.0.0-beta.4
  image_picker: ^1.0.5
  cached_network_image: ^3.3.0

  # Location Services
  geolocator: ^13.0.3

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  path: ^1.9.1
  logger: ^2.5.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Generation
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.7
  freezed: ^3.0.4
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
