name: invlog_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # ✅ Updated Firebase Dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  firebase_core_web: ^2.21.1
  firebase_auth_web: ^5.14.1
  firebase_storage_web: ^3.10.11
  cloud_firestore_web: ^4.4.5

  # ✅ State Management
  provider: ^6.1.1

  # ✅ Secure Storage
  flutter_secure_storage: ^10.0.0-beta.4

  # ✅ Location Services
  geolocator: ^13.0.3

  # ✅ Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  path: ^1.8.3
  logger: ^2.0.2+1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  google_sign_in: ^6.1.6
  js: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.7
  freezed: ^3.0.4
  json_serializable: ^6.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/