// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9G4JEPPutfRlEXOXgyORXMMEP4WH_SqY',
    appId: '1:83361214380:web:a440aeb5a5da79945e9409',
    messagingSenderId: '83361214380',
    projectId: 'invlog-test',
    authDomain: 'invlog-test.firebaseapp.com',
    storageBucket: 'invlog-test.appspot.com',
    measurementId: 'G-4VHQMEMG9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9kIs-V0cgBBEQMtYIfcnQXOiK78vDW9I',
    appId: '1:83361214380:android:b5e9fe05d798332a5e9409',
    messagingSenderId: '83361214380',
    projectId: 'invlog-test',
    storageBucket: 'invlog-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfC27r4hNV_h1arswKZ2bB27ysB8EAzSo',
    appId: '1:83361214380:ios:b2ac85f38e5fa2cc5e9409',
    messagingSenderId: '83361214380',
    projectId: 'invlog-test',
    storageBucket: 'invlog-test.appspot.com',
    iosBundleId: 'com.invlog.app',
  );
}
